version: '3'
services:
  financial_analysis_app:
    platform: linux/amd64
    restart: always
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./server:/app

