version: '3'
services:
  financial_analysis_flask_app:
    platform: linux/amd64
    restart: always
    build:
      context: ./server/flask
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./server/flask:/flask_app
  financial_analysis_express_app:
    build:
        context: ./server/express
        dockerfile: Dockerfile

